import type { ConditionModule } from '../conditions/types.js';
import type {
  MedOrder,
  MedicationSummary,
  PatientContext,
  RiskAnswer,
  RiskFinding,
  SafetyFinding,
  ScoreResult,
} from '../types.js';

/**
 * Deterministic safety screen run against the drafted regimen.
 *
 * Allergy matches are `critical` and gate clinician approval in the dashboard.
 * Duplicates and interactions are warnings — real, but a clinician's call.
 * Nothing here is generated by a model.
 */

/** Small, explicit interaction table. Extending it is a clinical review task. */
const INTERACTIONS: Array<{ a: string; b: string; message: string }> = [
  {
    a: 'sertraline',
    b: 'tramadol',
    message: 'SSRI with tramadol increases serotonin syndrome and seizure risk.',
  },
  {
    a: 'sertraline',
    b: 'warfarin',
    message: 'SSRIs increase bleeding risk with warfarin; INR monitoring is needed.',
  },
  {
    a: 'sertraline',
    b: 'linezolid',
    message: 'Contraindicated combination — serotonin syndrome risk.',
  },
  {
    a: 'formoterol',
    b: 'propranolol',
    message: 'Non-selective beta blockers antagonise beta-agonist bronchodilation.',
  },
  {
    a: 'prednisone',
    b: 'ibuprofen',
    message: 'Corticosteroid with an NSAID increases gastrointestinal bleeding risk.',
  },
];

function normalise(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim();
}

function tokensFor(input: { display: string; ingredients?: string[] }): string[] {
  if (input.ingredients?.length) return input.ingredients.map(normalise);
  return normalise(input.display).split(' ').filter((t) => t.length > 3);
}

function allergyMatches(allergy: string, med: MedOrder): boolean {
  const allergyToken = normalise(allergy);
  if (!allergyToken) return false;
  return tokensFor(med).some(
    (token) => token === allergyToken || token.includes(allergyToken) || allergyToken.includes(token),
  );
}

function duplicateMatches(current: MedicationSummary, med: MedOrder): string | undefined {
  const currentTokens = new Set(tokensFor(current));
  const shared = tokensFor(med).find((token) => currentTokens.has(token));
  return shared;
}

export function checkRegimenSafety(
  regimen: MedOrder[],
  context: Pick<PatientContext, 'allergies' | 'currentMedications'>,
): SafetyFinding[] {
  const findings: SafetyFinding[] = [];

  for (const med of regimen) {
    for (const allergy of context.allergies) {
      if (allergyMatches(allergy, med)) {
        findings.push({
          severity: 'critical',
          code: 'allergy-match',
          medication: med.display,
          message: `Recorded allergy to "${allergy}" matches ${med.display}. A clinician must acknowledge this before the plan can be approved.`,
        });
      }
    }

    for (const current of context.currentMedications) {
      const shared = duplicateMatches(current, med);
      if (shared) {
        findings.push({
          severity: 'warning',
          code: 'duplicate-therapy',
          medication: med.display,
          message: `${med.display} overlaps with the active medication "${current.display}" (shared ingredient: ${shared}). Confirm whether this is a replacement or an addition.`,
        });
      }

      for (const rule of INTERACTIONS) {
        const medTokens = tokensFor(med);
        const currentTokens = tokensFor(current);
        const hit =
          (medTokens.includes(rule.a) && currentTokens.includes(rule.b)) ||
          (medTokens.includes(rule.b) && currentTokens.includes(rule.a));
        if (hit) {
          findings.push({
            severity: 'warning',
            code: 'interaction',
            medication: med.display,
            message: `${med.display} with "${current.display}": ${rule.message}`,
          });
        }
      }
    }
  }

  if (regimen.length === 0) {
    findings.push({
      severity: 'info',
      code: 'note',
      message: 'This protocol step drafts no medication. Review is still required.',
    });
  }

  return dedupe(findings);
}

export function evaluateRisk(
  module: ConditionModule,
  riskAnswers: RiskAnswer[],
  score: ScoreResult,
): RiskFinding[] {
  try {
    return module.riskRules(riskAnswers, score);
  } catch {
    return [
      {
        severity: 'warning',
        code: 'risk-rules-failed',
        message: 'Risk rules could not be evaluated for this call. Review the raw answers manually.',
      },
    ];
  }
}

export function hasCritical(findings: Array<{ severity: string }>): boolean {
  return findings.some((f) => f.severity === 'critical');
}

/**
 * A critical risk finding forces escalation even when the score band alone
 * would not — for example a prior asthma ICU admission with a mid-range ACT.
 */
export function shouldEscalate(input: {
  urgentStep: boolean;
  safety: SafetyFinding[];
  risks: RiskFinding[];
}): boolean {
  return input.urgentStep || hasCritical(input.safety) || hasCritical(input.risks);
}

function dedupe(findings: SafetyFinding[]): SafetyFinding[] {
  const seen = new Set<string>();
  return findings.filter((finding) => {
    const key = `${finding.code}|${finding.medication ?? ''}|${finding.message}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
